services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    PrinterTheme\Twig\HomepageProductExtension:
        tags: ['twig.extension']

    PrinterTheme\Serializer\ImageNormalizer:
        tags:
            - { name: 'serializer.normalizer', priority: 100 }

sylius_twig_hooks:
    hooks:
        sylius_shop.base.header.navbar.menu:
            repair_service:
                template: '@SyliusShop/shared/layout/base/header/navbar/menu/repair_nav_link.html.twig'
                priority: -100
