sylius_api:
    resource: "@SyliusApiBundle/Resources/config/routing.yml"
    prefix: "%sylius.security.api_route%"

sylius_offers_api:
    resource: "@SyliusOffersPlugin/Resources/config/api_routes.yaml"
    prefix: /api/v1

#sylius_repair_service_api:
#    resource: "@SyliusRepairServicePlugin/Resources/config/api_routes.yaml"
#    prefix: /api/v1

sylius_best_seller_api:
    resource: "@SyliusBestSellerPlugin/Resources/config/api_routes.yaml"
    prefix: /api/v1

sylius_banner_api:
    resource: "@SyliusBannerPlugin/Resources/config/routing/shop.yaml"
    prefix: /api/v1

