sylius_offers_click:
    path: /offers/{id}/click
    controller: SyliusOffersPlugin\Controller\ClickController::trackClick

sylius_chargily:
    resource: "@SyliusChargilyPlugin/Resources/config/routing.yaml"
